### ISSUE TITLE
大佬  能不能对接各大注册API

### ISSUE THREAD

**Issue by logdns** [ypq123456789/domainkeeper#1]
大佬  
@能不能对接各大注册API (这样就免去输入信息, 直接API 抓取)
@可以设置tg到期推送,bark推送
@ (还有设置一个访问管控,可以只能自己查看)

😄 纯属我自己乱幻想,请勿介意

**Comment by ypq123456789** [comment]
对接各大注册商的API不太现实，因为太多了，做起来要吐血了。我想的是对接whois API, 如果你有免费的，可以分享给我，如果你有钱愿意付费，也可以分享给我接口测试哈
另外我还做了对接cloudflare API的功能，这个目前没什么太大问题了，可以直接识别自己CF上的所有域名，我只是在调试中 还没有放到github里面
推送这个慢慢来吧 先把这个对接whois给做好
访问管控倒是简单，但是这个优先级比较低，其实就是给网页加个密码就可以，然后跟哪吒差不多

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月8日(周一) 中午11:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ypq123456789/domainkeeper] 大佬  能不能对接各大注册API (Issue #1)




 
大佬
 @能不能对接各大注册API (这样就免去输入信息, 直接API 抓取)
 @可以设置tg到期推送,bark推送
 @ (还有设置一个访问管控,可以只能自己查看)
 
😄 纯属我自己乱幻想,请勿介意

**Comment by logdns** [comment]
我没有搞过whois API的 哈哈 我一般用 who.is 和whois.sc(这个好像是每天查询次数很低)
cloudflare API的功能不错呀  我都用cloudflare   
期待 感谢这么好的源码
